-- Copies of module and plugin commands are hidden on the Custom Commands
-- page until the user edits them (saves the graph or restores a version).
-- The module pages still find and toggle them; the bot ignores the flag.

ALTER TABLE commands ADD COLUMN hidden INTEGER NOT NULL DEFAULT 0 CHECK (hidden IN (0, 1));

-- Existing copies the user never saved (only the seeded version exists).
UPDATE commands SET hidden = 1
WHERE builtin = 0 AND kind = 'command' AND deleted_at IS NULL
  AND (SELECT COUNT(*) FROM command_versions v WHERE v.command_id = commands.id) = 1
  AND (
    plugin_id IS NOT NULL
    OR EXISTS (
      SELECT 1 FROM command_groups g
      JOIN (VALUES
    ('Birthday', 'birthday add'),
    ('Birthday', 'birthday delete'),
    ('Birthday', 'birthday list'),
    ('Economy', 'balance'),
    ('Economy', 'economy-add'),
    ('Economy', 'economy-remove'),
    ('Economy', 'leaderboard'),
    ('Economy', 'pay'),
    ('Free Games', 'free-games'),
    ('Giveaways', 'giveaway-create'),
    ('Giveaways', 'giveaway-delete'),
    ('Giveaways', 'giveaway-end'),
    ('Giveaways', 'giveaway-list'),
    ('Giveaways', 'giveaway-reroll'),
    ('Invite Tracker', 'invite-leaderboard'),
    ('Invite Tracker', 'invite-reset'),
    ('Invite Tracker', 'invites'),
    ('Leveling', 'level edit-xp'),
    ('Leveling', 'level leaderboard'),
    ('Leveling', 'level reset-leaderboard'),
    ('Leveling', 'rank'),
    ('Moderation', 'announce'),
    ('Moderation', 'automods'),
    ('Moderation', 'avatar'),
    ('Moderation', 'ban'),
    ('Moderation', 'banlist'),
    ('Moderation', 'case'),
    ('Moderation', 'channel'),
    ('Moderation', 'clearhistory'),
    ('Moderation', 'clearwarnings'),
    ('Moderation', 'deafen'),
    ('Moderation', 'history'),
    ('Moderation', 'kick'),
    ('Moderation', 'lock'),
    ('Moderation', 'mute'),
    ('Moderation', 'nick'),
    ('Moderation', 'note'),
    ('Moderation', 'notes'),
    ('Moderation', 'purge'),
    ('Moderation', 'removecase'),
    ('Moderation', 'removenote'),
    ('Moderation', 'role'),
    ('Moderation', 'serverinfo'),
    ('Moderation', 'slowmode'),
    ('Moderation', 'tempban'),
    ('Moderation', 'temprole'),
    ('Moderation', 'unban'),
    ('Moderation', 'undeafen'),
    ('Moderation', 'unlock'),
    ('Moderation', 'unmute'),
    ('Moderation', 'userinfo'),
    ('Moderation', 'voicekick'),
    ('Moderation', 'voicemute'),
    ('Moderation', 'voiceunmute'),
    ('Moderation', 'warn'),
    ('Moderation', 'warnings'),
    ('Modmail', 'modmail block'),
    ('Modmail', 'modmail close'),
    ('Modmail', 'modmail reply'),
    ('Modmail', 'modmail unblock'),
    ('Music', 'loop'),
    ('Music', 'lyrics'),
    ('Music', 'nowplaying'),
    ('Music', 'pause'),
    ('Music', 'play'),
    ('Music', 'queue'),
    ('Music', 'resume'),
    ('Music', 'shuffle'),
    ('Music', 'skip'),
    ('Music', 'stop'),
    ('Music', 'volume'),
    ('Polls', 'poll-create'),
    ('Polls', 'poll-delete'),
    ('Polls', 'poll-find'),
    ('Polls', 'poll-list'),
    ('Servermanagement', 'memory'),
    ('Servermanagement', 'ping'),
    ('Servermanagement', 'say'),
    ('Servermanagement', 'serverstats'),
    ('Servermanagement', 'uptime'),
    ('Suggestions', 'suggest'),
    ('Suggestions', 'suggest-approve'),
    ('Suggestions', 'suggest-list'),
    ('Suggestions', 'suggest-reject'),
    ('Ticket System', 'ticket add'),
    ('Ticket System', 'ticket automation'),
    ('Ticket System', 'ticket close'),
    ('Ticket System', 'ticket create'),
    ('Ticket System', 'ticket delete'),
    ('Ticket System', 'ticket remove'),
    ('Ticket System', 'ticket reopen'),
    ('Ticket System', 'ticket setup'),
    ('Ticket System', 'ticket update-counts')
      ) AS p ON g.name = p.column1 AND commands.name = p.column2
      WHERE g.id = commands.group_id
    )
  );
