#!/usr/bin/env node
// Creates a new plugin from the template: the base plus the features you pick.
//
//   npm run create -- <id> [--features nodes,voice,api | all] [--name "My Plugin"]
//                         [--description "..."] [--developer "..."] [--secret WEATHER]
//   npm run create -- --list
//
// A plugin is built in layers (BotHub shared/plugin-format.md):
//   commands/  events/  services/  nodes/  dashboard/   ->  BotHub SDK  ->  Core
// Every feature in parts/features/<name>/ brings files for these layers
// plus feature.json (permissions, nodes, commands, events, tasks,
// secrets, settings). They are merged into bothub.json,
// dashboard/settings.json, lang/*.json and the generated index.js.
import { cp, mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { check } from './lib/check.mjs';
import { installTestKit, marketDir } from './lib/plugins.mjs';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const templateDir = join(root, 'parts');
const featuresDir = join(templateDir, 'features');
// Fixed order: generated files read the same every time.
const ORDER = ['nodes', 'dashboard', 'commands', 'storage', 'messages', 'events', 'tasks', 'api', 'voice'];

const fail = (text) => {
  console.error(`create: ${text}`);
  process.exit(1);
};

function parseArgs(argv) {
  const out = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith('--')) {
      const [k, v] = a.slice(2).split('=', 2);
      out[k] = v ?? (argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[++i] : true);
    } else out._.push(a);
  }
  return out;
}

async function files(dir) {
  const out = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...(await files(p)));
    else out.push(p);
  }
  return out;
}

const readJson = async (p) => JSON.parse(await readFile(p, 'utf8'));
const unique = (list) => [...new Set(list)];
const byKey = (list, key) => [...new Map(list.map((x) => [x[key], x])).values()];
const ident = (name) => name.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());

function bothubJson(base, parts) {
  const all = (k) => parts.flatMap((p) => p[k] ?? []);
  const b = structuredClone(base);
  b.sdk.permissions = unique([...b.sdk.permissions, ...all('permissions')]);
  const out = {};
  // Key order as in plugin-format.md: identity, SDK, then the layers.
  for (const k of ['$schema', 'schemaVersion', 'id', 'name', 'version', 'description', 'developer', 'license', 'sdk', 'main']) {
    if (k in b) out[k] = b[k];
  }
  if (all('commands').length) out.commands = unique(all('commands'));
  if (all('events').length) out.events = unique(all('events'));
  const services = {};
  if (all('tasks').length) services.tasks = byKey(all('tasks'), 'name');
  if (all('secrets').length) services.secrets = unique(all('secrets'));
  if (Object.keys(services).length) out.services = services;
  if (all('nodes').length) out.nodes = unique(all('nodes'));
  if (all('settings').length) out.dashboard = { settings: 'dashboard/settings.json' };
  out.lang = b.lang;
  return out;
}

function indexJs(b) {
  const nodes = b.nodes ?? [];
  const events = b.events ?? [];
  const hasTasks = Boolean(b.services?.tasks?.length);
  const imports = [
    ...nodes.map((n) => `import ${ident(n)} from './nodes/${n}.js';`),
    ...events.map((e) => `import ${e} from './events/${e}.js';`),
    ...(hasTasks ? ["import { tasks } from './services/tasks.js';"] : []),
  ];
  const lines = [
    '// Entry file ("main" in bothub.json), generated by scripts/create.mjs.',
    '// It joins the layers into the plugin object the BotHub SDK runs:',
    '//   nodes/<name>.js    -> blocks   (definition: nodes/<name>.json)',
    '//   events/<event>.js  -> events   (names: bothub.json "events")',
    '//   services/tasks.js  -> tasks    (schedule: bothub.json "services.tasks")',
    '// commands/ and dashboard/ need no code; the core reads them from bothub.json.',
    '// Adding a node: nodes/<name>.json + nodes/<name>.js, its name in bothub.json "nodes", and a line below.',
    ...imports,
    '',
    "/** @type {import('@bothub/sdk').PluginDefinition} */",
    'export default {',
    '  async onEnable(ctx) {',
    '    await ctx.logger.info(`${ctx.plugin.getId()} ${ctx.plugin.getVersion()} enabled for bot ${ctx.botId}`);',
    '  },',
    `  blocks: { ${nodes.map((n) => (ident(n) === n ? n : `${n}: ${ident(n)}`)).join(', ')} },`,
  ];
  if (events.length) lines.push(`  events: { ${events.join(', ')} },`);
  if (hasTasks) lines.push('  tasks,');
  lines.push('};', '');
  return lines.join('\n');
}

function readme(b, features, all) {
  const sdk = b.sdk.permissions;
  return [
    `# ${b.name}`,
    '',
    b.description,
    '',
    `Version ${b.version} · developer: ${b.developer.name} · license: ${b.license ?? '-'}`,
    '',
    '## Structure',
    '',
    '```',
    'Plugin',
    `  ├── Commands    commands/   ${(b.commands ?? []).map((c) => c.replace(/^commands\//, '')).join(', ') || '-'}`,
    `  ├── Events      events/     ${(b.events ?? []).join(', ') || '-'}`,
    `  ├── Services    services/   ${[...(b.services?.tasks ?? []).map((t) => `task ${t.name}`), ...(b.services?.secrets ?? []).map((e) => `secret ${e}`)].join(', ') || 'helpers only'}`,
    `  ├── Nodes       nodes/      ${(b.nodes ?? []).join(', ') || '-'}`,
    `  └── Dashboard   dashboard/  ${b.dashboard ? 'settings page' : '-'}`,
    '        │',
    '        ▼',
    '   BotHub SDK  →  Core  →  Discord · DB · Redis',
    '```',
    '',
    '## SDK permissions the admin must enable',
    '',
    ...(sdk.length ? sdk.map((p) => `- \`${p}\``) : ['None.']),
    '',
    ...(b.services?.secrets?.length
      ? ['## Secrets', '', 'Create under Admin → API / Secrets (the address too) and share them with the plugin in the App Store:', '', ...b.services.secrets.map((e) => `- \`${e}\``), '']
      : []),
    '## Built from',
    '',
    ...features.map((f) => `- **${all[f].title}**: ${all[f].description}`),
    '',
    '## Develop',
    '',
    '```',
    'npm test                         # in this folder: the plugin tests',
    '',
    '# in Bothub/sdk/market (tools of the BotHub repo):',
    `npm run validate -- ${b.id}`,
    `npm run pack -- ${b.id}          # dist/${b.id}-<version>.zip + SHA-256`,
    'npm run index                    # index.json of the market repo',
    '```',
    '',
    `Publish: GitHub Release \`${b.id}-<version>\` of the market repo with the zip as asset, then commit index.json.`,
    '',
    'Raise `version` in `bothub.json` for every release.',
    '',
  ].join('\n');
}

const all = {};
for (const name of await readdir(featuresDir)) all[name] = await readJson(join(featuresDir, name, 'feature.json'));
const args = parseArgs(process.argv.slice(2));

if (args.list) {
  for (const f of ORDER) console.log(`${f.padEnd(10)} ${all[f].title} · needs [${all[f].needs.join(', ')}] · SDK [${all[f].permissions.join(', ')}]`);
  process.exit(0);
}

// Plugin ids are plugin_<name> (lowercase, digits, _); "weather" becomes plugin_weather.
const given = String(args._[0] ?? '').replace(/-/g, '_');
const id = given.startsWith('plugin_') ? given : `plugin_${given}`;
if (!given || !/^plugin_[a-z0-9_]{1,57}$/.test(id)) fail('give a plugin name: a-z, 0-9, _ (e.g. "npm run create -- weather --features nodes" -> plugin_weather)');
// Secret names of the "api" feature: <SECRET>_URL (address) and <SECRET>_KEY.
const secret = String(args.secret ?? 'EXAMPLE').toUpperCase();
if (!/^[A-Z][A-Z0-9_]{1,30}$/.test(secret)) fail('--secret must look like WEATHER');
const name = String(args.name ?? id.slice(7).split('_').filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join(' ')).slice(0, 60);
const description = String(args.description ?? `${name} for BotHub.`).slice(0, 300);
const developer = String(args.developer ?? 'BotHub community').slice(0, 60);

const wanted = args.features === 'all' ? [...ORDER] : String(args.features ?? 'nodes').split(',').map((s) => s.trim()).filter(Boolean);
for (const f of wanted) if (!all[f]) fail(`unknown feature "${f}" (see --list)`);
for (let changed = true; changed; ) {
  changed = false;
  for (const f of wanted) for (const n of all[f].needs) if (!wanted.includes(n)) { wanted.push(n); changed = true; }
}
const features = ORDER.filter((f) => wanted.includes(f));
const parts = features.map((f) => all[f]);

const out = resolve(String(args.out ?? join(marketDir, id)));
if (existsSync(out)) fail(`${relative(process.cwd(), out)} exists already`);
await mkdir(out, { recursive: true });

// Base and feature files (feature.json and lang are merged instead).
await cp(join(templateDir, 'base'), out, { recursive: true, filter: (src) => !src.includes(`${sep}lang`) });
for (const f of features) {
  const dir = join(featuresDir, f);
  for (const file of await files(dir)) {
    const rel = relative(dir, file);
    if (rel === 'feature.json' || rel.startsWith(`lang${sep}`)) continue;
    if (existsSync(join(out, rel))) fail(`feature "${f}" would overwrite ${rel.split(sep).join('/')}`);
    await mkdir(join(out, rel, '..'), { recursive: true });
    await cp(file, join(out, rel));
  }
}

const b = bothubJson(await readJson(join(templateDir, 'base', 'bothub.json')), parts);
await writeFile(join(out, 'bothub.json'), JSON.stringify(b, null, 2) + '\n');
const allSettings = parts.flatMap((p) => p.settings ?? []);
const settings = byKey(allSettings, 'key');
if (settings.length !== allSettings.length) fail('two features define the same setting key');
if (settings.length) {
  await mkdir(join(out, 'dashboard'), { recursive: true });
  await writeFile(join(out, 'dashboard', 'settings.json'), JSON.stringify({ fields: settings }, null, 2) + '\n');
}
await mkdir(join(out, 'lang'), { recursive: true });
for (const code of ['en', 'de']) {
  const texts = await readJson(join(templateDir, 'base', 'lang', `${code}.json`));
  for (const f of features) {
    const p = join(featuresDir, f, 'lang', `${code}.json`);
    if (existsSync(p)) Object.assign(texts, await readJson(p));
  }
  await writeFile(join(out, 'lang', `${code}.json`), JSON.stringify(texts, null, 2) + '\n');
}
await writeFile(join(out, 'index.js'), indexJs(b));
await writeFile(join(out, 'README.md'), readme(b, features, all));

// Placeholders in every text file.
const values = { __ID__: id, __NAME__: name, __DESCRIPTION__: description, __DEVELOPER__: developer, __URL_SECRET__: `${secret}_URL`, __KEY_SECRET__: `${secret}_KEY` };
for (const file of await files(out)) {
  if (!/\.(js|mjs|json|md)$/.test(file)) continue;
  let text = await readFile(file, 'utf8');
  for (const [k, v] of Object.entries(values)) {
    // JSON files get JSON-escaped values (quotes in a name or description).
    const val = file.endsWith('.json') ? JSON.stringify(v).slice(1, -1) : v;
    text = text.split(k).join(val);
  }
  await writeFile(file, text);
}

await installTestKit(out);
console.log(`created ${relative(process.cwd(), out)} with: ${features.join(', ')}`);
console.log(`SDK permissions: ${b.sdk.permissions.join(', ') || 'none'}`);
// The new plugin must pass the same checks as a published one.
const problems = await check(out);
if (problems.length) fail(['the new plugin does not pass validate:', ...problems.map((p) => `  - ${p}`)].join('\n'));
console.log('validate: ok. next: npm test');
